canonical: https://gematik.de/fhir/ISiK
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Modul Medikation
name: Implementierungsleitfaden ISiK-Modul Medikation
status: draft