canonical: https://gematik.de/fhir/ISiK/v2
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Modul Medikation
name: Implementierungsleitfaden ISiK-Modul Medikation
status: active
version: "2.0.0-ballot"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: ISiK@gematik.de
dependencies:
  de.medizininformatikinitiative.kerndatensatz.medikation: 1.0.10
  hl7.fhir.r4.core: 4.0.1
  de.gematik.isik-basismodul: 2.0.0-ballot2
