canonical: https://gematik.de/fhir/ISiK
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Modul Medikation
name: Implementierungsleitfaden ISiK-Modul Medikation
status: draft
version: "1.0.0"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: ISiK@gematik.de
dependencies:
  de.medizininformatikinitiative.kerndatensatz.medikation: 1.0.10
  hl7.fhir.r4.core: 4.0.1
