canonical: https://gematik.de/fhir/isik/v3/Medikation
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
version: 3.0.3
dependencies:
  de.medizininformatikinitiative.kerndatensatz.medikation: 1.0.11
  hl7.fhir.r4.core: 4.0.1
  de.gematik.isik-basismodul: 3.0.x
