canonical: https://gematik.de/fhir/isik/v4/Medikation
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
version: 3.0.1
dependencies:
  de.basisprofil.r4: 1.5.0-ballot
  hl7.fhir.r4.core: 4.0.1
  de.gematik.isik-basismodul: 3.0.3
